name       : oniguruma
version    : 6.9.6
release    : 3
source     :
    - https://github.com/kkos/oniguruma/releases/download/v6.9.6/onig-6.9.6.tar.gz : bd0faeb887f748193282848d01ec2dad8943b5dfcb8dc03ed52dcc963549e819
license    : BSD-2-Clause
summary    : Oniguruma is a modern and flexible regular expressions library
component  : programming.library
description: |
    Oniguruma is a modern and flexible regular expressions library. It encompasses features from different regular expression implementations that traditionally exist in different languages.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
